server:
  host: "0.0.0.0"
  port: 8080
  grpc_port: 50051
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  host: "localhost"
  port: 5432
  user: "messenger_user"
  name: "messenger_db"
  ssl_mode: "disable"
  max_conns: 20

redis:
  host: "localhost"
  port: 6379
  db: 0

jwt:
  expiration_hours: 24
  refresh_expiration_days: 30

log:
  level: "info"
  format: "json"
  output: "stdout"
  add_source: true

vault:
  enabled: true
  address: "http://localhost:8200"
  mount_path: "secret"
  namespace: "messenger"

features:
  websocket_enabled: true
  rate_limit_enabled: true
  debug_enabled: false